#!/usr/bin/env bash

KEY="$HOME/.ssh/agenix"

if [ $# -ne 1 ] || ! [[ "$1" =~ \.age$ ]]; then
  echo "Usage: $0 <path/to/secret.age>"
  exit 1
fi

src="$1"
tmp="/tmp/$(basename "$src" .age).$$"

age -d -i $KEY "$src" > "$tmp"
sum_before=$(md5sum "$tmp")
${EDITOR:-vim} "$tmp"
sum_after=$(md5sum "$tmp")

if [ "$sum_before" != "$sum_after" ]; then
  age -e -R $KEY.pub -o "$src" "$tmp"
else
  echo "No changes."
fi
rm -f "$tmp"

