#!/usr/bin/env bash

if [ $# -ne 3 ]; then
  echo "Usage: $0 <old-email> <new-name> <new-email>"
  exit 1
fi

old_email="$1"
new_name="$2"
new_email="$3"

git filter-branch -f --commit-filter "
  if [ \"\$GIT_AUTHOR_EMAIL\" = \"$old_email\" ];
  then
    GIT_AUTHOR_NAME=\"$new_name\";
    GIT_AUTHOR_EMAIL=\"$new_email\";
    git commit-tree \"\$@\";
  else
    git commit-tree \"\$@\";
  fi" HEAD

