#!/usr/bin/env sh

show_help () {
cat << HALP
USAGE
  $(basename $0) OPTIONS COUNT

OPTIONS
  a/alpha     alphabet
  n/num       numeric
  an/alphanum alphanumeric
  c/r/char    all ascii characters
HALP
}

gen () {
  tr -dc $1 < /dev/urandom | head -c $2 && echo
}

case $1 in
  "a"|"alpha")
    gen 'A-Za-z' $2
    ;;
  "n"|"num")
    gen '0-9' $2
    ;;
  "an"|"alphanum")
    gen 'A-Za-z0-9' $2
    ;;
  "c"|"r"|"char")
    gen 'A-Za-z0-9#\$%&@^`~.,:;\"\'\''\\/|_\-<*+!?={[()]}' $2
    ;;
  *)
    show_help
    ;;
esac

