#!/bin/sh

echo

# regular
printf %s '     '
for color in 0 1 2 3 4 5 6 7; do
  tput setab ${color}
  tput setaf $((${color}+8))
  printf %s "${color}  "
  tput setab $((${color}+8))
  printf %s ' '
  tput sgr0
  printf %s '  '
done
tput sgr0

echo

# bold
printf %s '     '
for color in 8 9 10 11 12 13 14 15; do
  tput setab $((${color}-8))
  printf %s ' '
  tput setab ${color}
  tput setaf $((${color}-8))
  if [ $color -lt 10 ]; then
    printf %s "  ${color}"
  elif [ $color -gt 9 ]; then
    printf %s " ${color}"
  fi
  tput sgr0
  printf %s '  '
done
tput sgr0

echo
echo

